"""empty message

Revision ID: 4aa8f5b445fb
Revises: a2405bfcd62d
Create Date: 2023-12-04 12:46:06.541246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa8f5b445fb'
down_revision: Union[str, None] = 'a2405bfcd62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'asset_ype')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('asset_ype', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
