"""empty message

Revision ID: a00b7e28996d
Revises: d9813f70a3dd
Create Date: 2023-12-14 03:16:21.523277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00b7e28996d'
down_revision: Union[str, None] = 'd9813f70a3dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_levels', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_levels', 'weight')
    # ### end Alembic commands ###
