"""empty message

Revision ID: afde40639637
Revises: 
Create Date: 2023-12-03 20:54:34.678106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afde40639637'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cripto_levels',
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('level', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('asset_type', sa.String(length=10), nullable=True),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('stock_levels',
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('level', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_levels')
    op.drop_table('stocks')
    op.drop_table('cripto_levels')
    # ### end Alembic commands ###
